version: 2

jobs:
    js-build:
        docker:
            - image: electronuserland/builder:wine
        steps:
            - checkout
            - run: yarn install
            - run: npm run build

    linux-build:
        docker:
            - image: electronuserland/builder:wine
        steps:
            - checkout
            - run: yarn install
            - run: ./node_modules/.bin/electron-rebuild
            - run: npm run package-linux
            - store_artifacts:
                path: ~/project/release

    mac-build:
        macos:
            xcode: "9.0"
        steps:
            - checkout
            - run: yarn install
            - run: ./node_modules/.bin/electron-rebuild
            - run: npm run package
            - store_artifacts:
                path: ~/project/release

workflows:
    version: 2
    development:
        jobs:
            - js-build:
                  filters:
                      tags:
                          ignore: /.*/
                      branches:
                          ignore: /master|alpha/
            - linux-build:
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          only: /master|alpha/
            - mac-build:
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          only: /master|alpha/